#!/usr/bin/expect -f
set timeout 1200
set user $env(DBUSER)
set host $env(DBHOST)
set pass $env(DBPASSWORD)
set name $env(DBNAME)

spawn ./symfony openpne:install
expect "mysql"
send "mysql\r"
expect "username"
send "$user\r"
expect "password"
send "$pass\r"
expect "hostname"
send "$host\r"
expect "port"
send "\r"
expect "database name"
send "$name\r"
expect "OK"
send "Y\r"
expect eof
